version: '3'

services:
  person-detection-service:
    build: .
    container_name: person-detection-service
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./static:/app/static
      - ./custom_dataset:/app/custom_dataset
    restart: unless-stopped 